export type Currency = "AUD" | "USD" | "GBP" | "EUR" | "CAD" | "NZD";
export type Plan = "starter" | "small" | "medium" | "large" | "xlarge" | "unlimited";

// Plan features and limits
export const planFeatures = {
  free: {
    name: "Free Trial",
    guestLimit: 8,
    albumLimit: 1,
    themeLimit: 1,
    uploadWindowMonths: 3,
    downloadWindowMonths: 12,
    customBranding: false,
    videoGuestbook: false,
    publicAccess: false,
    supportLevel: "standard" as const,
  },
  starter: {
    name: "Starter Plan",
    guestLimit: 10,
    albumLimit: 1,
    themeLimit: 1,
    uploadWindowMonths: 3,
    downloadWindowMonths: 12,
    customBranding: false,
    videoGuestbook: false,
    publicAccess: true,
    supportLevel: "standard" as const,
  },
  small: {
    name: "Small Plan", 
    guestLimit: 25,
    albumLimit: 2,
    themeLimit: 5,
    uploadWindowMonths: 3,
    downloadWindowMonths: 12,
    customBranding: false,
    videoGuestbook: false,
    publicAccess: true,
    supportLevel: "standard" as const,
  },
  medium: {
    name: "Medium Plan",
    guestLimit: 50,
    albumLimit: 3,
    themeLimit: 10,
    uploadWindowMonths: 6,
    downloadWindowMonths: 12,
    customBranding: false,
    videoGuestbook: true,
    publicAccess: true,
    supportLevel: "standard" as const,
  },
  large: {
    name: "Large Plan",
    guestLimit: 100,
    albumLimit: 5,
    themeLimit: 15,
    uploadWindowMonths: 12,
    downloadWindowMonths: 12,
    customBranding: false,
    videoGuestbook: true,
    publicAccess: true,
    supportLevel: "standard" as const,
  },
  xlarge: {
    name: "XLarge Plan",
    guestLimit: 200,
    albumLimit: 10,
    themeLimit: 15,
    uploadWindowMonths: 12,
    downloadWindowMonths: 12,
    customBranding: true,
    videoGuestbook: true,
    publicAccess: true,
    supportLevel: "priority" as const,
  },
  unlimited: {
    name: "Unlimited Plan",
    guestLimit: 999999,
    albumLimit: 999999,
    themeLimit: 999999,
    uploadWindowMonths: 12,
    downloadWindowMonths: 12,
    customBranding: true,
    videoGuestbook: true,
    publicAccess: true,
    supportLevel: "dedicated" as const,
  },
};

// Pricing matrix (amounts in minor units - cents)
export const pricingMatrix = {
  starter: { AUD: 2900, USD: 2000, GBP: 1500, EUR: 1800, CAD: 2600, NZD: 3100 },
  small: { AUD: 3900, USD: 2700, GBP: 2000, EUR: 2400, CAD: 3500, NZD: 4200 },
  medium: { AUD: 5900, USD: 4100, GBP: 3100, EUR: 3700, CAD: 5300, NZD: 6300 },
  large: { AUD: 7900, USD: 5500, GBP: 4200, EUR: 5000, CAD: 7100, NZD: 8500 },
  xlarge: { AUD: 10900, USD: 7600, GBP: 5800, EUR: 6900, CAD: 9800, NZD: 11700 },
  unlimited: { AUD: 14900, USD: 10400, GBP: 7900, EUR: 9400, CAD: 13400, NZD: 15900 },
};

// Import the actual Stripe Price IDs generated by setup-stripe-products.js
import { stripePriceIds as generatedPriceIds } from './stripe-price-ids';

// Use the generated Price IDs from Stripe
export const stripePriceIds: Record<Plan, Record<Currency, string>> = generatedPriceIds;

export function getPriceId(plan: Plan, currency: Currency): string {
  return stripePriceIds[plan][currency];
}

export function formatCurrency(amountMinor: number, currency: Currency): string {
  const amount = amountMinor / 100;
  const formatter = new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: currency,
  });
  return formatter.format(amount);
}

export function getPlanFeatures(plan: string) {
  return planFeatures[plan as keyof typeof planFeatures] || planFeatures.free;
}

export function getPrice(plan: Plan, currency: Currency): number {
  return pricingMatrix[plan][currency];
}

/**
 * Calculate the upgrade price difference between two plans
 */
export function getUpgradePrice(fromPlan: string, toPlan: Plan, currency: Currency): number {
  // Free plan has no cost
  if (fromPlan === 'free' || !fromPlan) {
    return getPrice(toPlan, currency);
  }
  
  // Can't upgrade to same or lower plan via delta pricing
  if (fromPlan === toPlan) {
    return 0;
  }
  
  // Check if fromPlan is a valid paid plan
  if (!(fromPlan in pricingMatrix)) {
    return getPrice(toPlan, currency);
  }
  
  const fromPrice = pricingMatrix[fromPlan as Plan][currency];
  const toPrice = pricingMatrix[toPlan][currency];
  
  // Return the difference (should always be positive for upgrades)
  return Math.max(0, toPrice - fromPrice);
}

/**
 * Check if one plan is higher than another
 */
export function isPlanUpgrade(fromPlan: string, toPlan: Plan): boolean {
  const planHierarchy = ['free', 'starter', 'small', 'medium', 'large', 'xlarge', 'unlimited'];
  const fromIndex = planHierarchy.indexOf(fromPlan || 'free');
  const toIndex = planHierarchy.indexOf(toPlan);
  
  return toIndex > fromIndex;
}

/**
 * Get all available upgrade options for a given plan
 */
export function getAvailableUpgrades(currentPlan: string): Plan[] {
  const planHierarchy: (string | Plan)[] = ['free', 'starter', 'small', 'medium', 'large', 'xlarge', 'unlimited'];
  const currentIndex = planHierarchy.indexOf(currentPlan || 'free');
  
  return planHierarchy.slice(currentIndex + 1) as Plan[];
}