// Generated by setup-stripe-products.js
// Do not edit manually - run the script again to regenerate

export const stripePriceIds = {
  essential: {
    AUD: "price_1SFmEGRbJmIvi7UlpOMTCbAJ",
    USD: "price_1SFmEHRbJmIvi7UlC21HWYSI",
    GBP: "price_1SFmEHRbJmIvi7UlAsU6AhBO",
    EUR: "price_1SFmEHRbJmIvi7UlzSDUFZrZ",
    CAD: "price_1SFmEHRbJmIvi7UlNFJhQC93",
    NZD: "price_1SFmEIRbJmIvi7UlnCJ5GyIw",
  },
  timeless: {
    AUD: "price_1SFmEIRbJmIvi7UllIiWgL72",
    USD: "price_1SFmEJRbJmIvi7Ull4kgKJKm",
    GBP: "price_1SFmEJRbJmIvi7Uls4idwcog",
    EUR: "price_1SFmEJRbJmIvi7Ul5yYJi96S",
    CAD: "price_1SFmEJRbJmIvi7UlCs4SDAZB",
    NZD: "price_1SFmEKRbJmIvi7UlKW6Mv4Jx",
  },
  premier: {
    AUD: "price_1SFmEKRbJmIvi7UlUJWlW45u",
    USD: "price_1SFmELRbJmIvi7Ulp2NQdysh",
    GBP: "price_1SFmELRbJmIvi7UlFJfIPy48",
    EUR: "price_1SFmELRbJmIvi7UliE39kfLL",
    CAD: "price_1SFmELRbJmIvi7UlbN0E0xVC",
    NZD: "price_1SFmEMRbJmIvi7UlOKRUEn9k",
  },
} as const;
