// Generated by setup-stripe-products.js
// Do not edit manually - run the script again to regenerate

export const stripePriceIds = {
  guest50: {
    AUD: "price_1S8DO7RZSAuj4M4XHpLODLLY",
    USD: "price_1S8DO7RZSAuj4M4XJCnSik3y",
    GBP: "price_1S8DO8RZSAuj4M4XosNhN359",
    EUR: "price_1S8DO8RZSAuj4M4XJzRFp313",
    CAD: "price_1S8DO8RZSAuj4M4XRVy9CxBM",
    NZD: "price_1S8DO9RZSAuj4M4X9GpWCLgY",
  },
  guest100: {
    AUD: "price_1S8DO9RZSAuj4M4XRG01eB7R",
    USD: "price_1S8DOARZSAuj4M4XJXcylrjO",
    GBP: "price_1S8DOARZSAuj4M4XRk6DER5x",
    EUR: "price_1S8DOARZSAuj4M4XOsmU7ArL",
    CAD: "price_1S8DOBRZSAuj4M4XtIVBMdjN",
    NZD: "price_1S8DOBRZSAuj4M4X7mSnOgdw",
  },
  unlimited: {
    AUD: "price_1S8DOCRZSAuj4M4XeqtwdFDr",
    USD: "price_1S8DOCRZSAuj4M4X1W1XW1wu",
    GBP: "price_1S8DOCRZSAuj4M4XFZIdkZbX",
    EUR: "price_1S8DODRZSAuj4M4X7AcfeQtS",
    CAD: "price_1S8DODRZSAuj4M4XKMSjAnwc",
    NZD: "price_1S8DODRZSAuj4M4XqpBo3Jy8",
  },
} as const;
